<?php
	$saved_Store = $block->savedstore();
	$savedAddressJson = json_decode($saved_Store,true);
?>
<div class="mystore-list">
	<div class="anotherstore">
		<p><?php echo __($block->getSearchText()); ?></p>
		<div class="storefinder-content error-message">
			<input type="text" id="mystore_zip" name="postalcode">	
			<button id="mystore_Search" type="button"><?php echo __('Find') ?></button>
			<?php if( isset($_SERVER['HTTPS'] ) ) :?>
		    	<span class="gps-locator-button">
					<button id="gpslocation_account" type="button"><?php echo __('Use My Location') ?></button>
				</span>
			<?php endif;?>
		</div>
		 	<div id="bullseye-banner-header">
		 		<div id="mystore-bullseye-banner-header-inner">
		    	<?php if($savedAddressJson):?>
		    		
						<p class="neareststore"><?php echo __($block->getSavedStoreTitle()); ?></p>
						<address>
							<div class="diveighty"><?php echo $savedAddressJson['city']; ?>
								<div><?php echo $savedAddressJson['address']; ?></div><br>
							</div>
	                		
	                		<div class="divtwenty">
	                			<div><?php echo $savedAddressJson['distance'].' mi'; ?></div>
								<div>
									<a href="<?php echo $block->getUrl('bullseye/removestore'); ?>" class="savestorelink">Remove</a>
								</div>	
							</div>
						</address>
				<?php endif;?>
				</div>
	    	</div>
	</div>
</div>


<script type="text/javascript">
	require(['jquery'],function($){
				
		var savedAddressid = <?php echo $block->getAddressID(); ?>;
		var savedStore = '<?php echo $block->savedstore(); ?>';

		var bullseyeLocator = (function ($) {
			
		    var absoluteUrl = ''; 
			var bullseyeApiKey = '<?php echo $block->getApiKey(); ?>';
			var bullseyeClientId = '<?php echo $block->getClientId(); ?>'; 
		    var displayLocName = true;
			var displayPhone = true;
		    var imagesDir = 'images'; 
			var locationTerm = 'store'; 
			var searchRadius = '25';
			
			var savestorelink = "<?php echo $block->getUrl('bullseye/savestore'); ?>";
			var removestorelink = "<?php echo $block->getUrl('bullseye/removestore'); ?>";

			var saveStoreText = "<?php echo __("Save"); ?>";
			var removeStoreText = "<?php echo __("Remove"); ?>";
			var savedstoretitle = "<?php echo __($block->getSavedStoreTitle()); ?>";
			var nosavedstoremsg = "<?php echo __($block->getNoSavedStoreMsg()); ?>";
			var nearbystoretitle = "<?php echo __($block->getNearByStoreTitle()); ?>";
			var searchstoretitle = "<?php echo __($block->getSearchStoreTitle()); ?>";
			var nostorenearbymsg = "<?php echo __($block->getNoStoreNearByMsg()); ?>";
			var locationservicedisablemsg;
			var nosearchstoremsg = "<?php echo __($block->getNoSearchStoreMsg()); ?>";
			var findstoreonmaplink = "<?php echo __($block->getFindOnMapLink()); ?>";
			
			//Do not modify
			var bullseyeWsUrl = 'https://ws.bullseyelocations.com';
			var headerDivId = 'mystore-bullseye-banner-header';
		    var headerInnerDivId = 'mystore-bullseye-banner-header-inner';
		    var headerLoaderId = 'mystore-bullseye-banner-header-loader';
		    var headerNoStoreId = 'mystore-bullseye-banner-header-no-store';
		    var headerNearestStoreId = 'mystore-bullseye-banner-header-nearest-store';
		    var beSrchCookieKey = "beloc_srchdata";
		    var storeCount = 0;
			
		    function buildUrl(lat, lon) {
		        var lat, lon;
		        
		        var url = bullseyeWsUrl + '/RestSearch.svc/DoSearch2?ClientId=' + bullseyeClientId + '&ApiKey=' + bullseyeApiKey + '&Latitude=' + lat + '&Longitude=' + lon + '&radius=' + searchRadius + '&StartIndex=0&PageSize=10&id=16779292';
		        
		        return url;
		    }
		    
		    function buildUrlZip(zip) {
		        
		        var url = bullseyeWsUrl + '/RestSearch.svc/DoSearch2?ClientId=' + bullseyeClientId + '&ApiKey=' + bullseyeApiKey + '&PostalCode=' + zip+ '&radius=' + searchRadius + '&StartIndex=0&PageSize=10';
		        
		        return url;
		    }

		    function createBaseHtml(){

		    	var zip = $('#mystore_zip').val();
                
			   	

		    	var addressH = '<div id="mystore-bullseye-banner-header-selected-store">';
		    	var savedAddressJson = JSON.parse(savedStore);
		    	
		    	if(savedAddressid != 0){
		    		addressH += '<div id="mystore-bullseye-banner-header-nearest-store">';
		    			addressH += '<p class="neareststore">'+savedstoretitle+'</p>';
		    			addressH += '<address><div class="diveighty">'+savedAddressJson.city+'<div>'+savedAddressJson.address+'</div><br></div>';
		    			addressH += '<div class="divtwenty"><div>'+savedAddressJson.distance+' mi</div>';
		    			addressH += '<div><a href="'+removestorelink+'" class="savestorelink">'+removeStoreText+'</a></div>';
		    		addressH += '</div></address></div>';
		    	}
		    	else{
		    		addressH += '<div id="mystore-bullseye-banner-header-nearest-store">';
		    			addressH += '<p class="neareststore">'+savedstoretitle+'</p>';
		    			addressH += '<p style="float:left;">'+nosavedstoremsg+'</p>';
		    		addressH += '</div>';
		    	}

		    	addressH += '</div>';
		    	addressH += '<div id="mystore-bullseye-banner-header-unselected-store">';
		    	if (zip.length == 5){
					addressH += '<p class="neareststore">'+searchstoretitle+'</p>';	
		    		addressH += '<p id="mystore-notfoundstoremsg" style="float:left;">'+nosearchstoremsg+'</p>';
			   	} else {
                	addressH += '<p class="neareststore">'+nearbystoretitle+'</p>';	
		    		addressH += '<p id="mystore-notfoundstoremsg" style="float:left;">'+nostorenearbymsg+'</p>';
               	} 
		    	
		    	addressH += '</div>';
		    	$('#mystore-bullseye-banner-header-inner').append(addressH);
		    }

		    function buildNewLocationHtml(id, locName, address, city, state, zip, phone, distance, countryCode, latitude, longitude){

		    	$('#mystore-notfoundstoremsg').remove();
		    	var addressH = '<div id="mystore-bullseye-banner-header-nearest-store">';

		    	if(id == savedAddressid){
		    		addressH += '<p class="neareststore">'+savedstoretitle+'</p>';
		    	}

		    	addressH += '<address><div class="diveighty">'+city+'<div>'+address+'</div><br></div>';
		    	addressH += '<div class="divtwenty"><div>'+distance+' mi</div>';
		    	if(id != savedAddressid){
		    		addressH += '<div><a href="'+savestorelink+'?addressid='+id+'&&city='+city+'&&address='+address+'&&distance='+distance+'&&CountryCode='+countryCode+'&&State='+state+'&&PostCode='+zip+'&&latitude='+latitude+'&&longitude='+longitude+'" class="savestorelink">'+saveStoreText+'</a></div>';		
		    	}
		    	else{
		    		addressH += '<div><a href="'+removestorelink+'" class="savestorelink">'+removeStoreText+'</a></div>';	
		    	}
		    	addressH += '</div></address></div>';
		    	
		    	if(id == savedAddressid){
		    		$('#mystore-bullseye-banner-header-selected-store').html(addressH);
		    	}
		    	else{
		    		$('#mystore-bullseye-banner-header-unselected-store').append(addressH);
		    	}


				$($('#' + headerLoaderId)).hide();
		        $($('#' + headerNoStoreId)).hide();
		        $($('#' + headerNearestStoreId)).show();
		        storeCount++;
		    }
		    
		    function showDefaultMessage(error) {
		    	if(location.protocol == 'https:')
		    	{
		    		if (navigator.geolocation) {
		                
		            	locationservicedisablemsg = error.message;
                           
		    		}
		    	} else {
		    			locationservicedisablemsg = "<?php echo __($block->getInsecureSiteMsg()); ?>";
		    	}

		    	if(savedAddressid == 0){

		    		var noStoreDiv = $('<div/>', { id: headerNoStoreId }).appendTo($('div#' + headerInnerDivId));
			        $(noStoreDiv).html('<p>'+locationservicedisablemsg+'</p>');
			        

			        $($('#' + headerLoaderId)).hide();
			        $($('#' + headerNearestStoreId)).hide();
			        $($('#' + headerNoStoreId)).show();
		    	}
		        
		    }

		    function getCookie (key) {
		        var name = key + "=";
		        var ca = document.cookie.split(';');
		        for(var i=0; i<ca.length; i++) {
		            var c = ca[i];
		            while (c.charAt(0)==' ') c = c.substring(1);
		            if (c.indexOf(name) == 0) return c.substring(name.length,c.length);
		        }
		        return "";
		    }

		    function setCookie (key, value, expMins) {
		        var d = new Date();
		        d.setTime(d.getTime() + (expMins*60*1000));
		        var expires = "expires="+d.toUTCString();
		        document.cookie = key + "=" + value + "; " + expires;
		    }  

		    return {
		        getLocation: function () {
			         var locate = this;
		            if (navigator.geolocation) {
		                navigator.geolocation.getCurrentPosition(
                            function (position) {
                                /*lat = 42.065540;
                                lon = -87.987372;*/
                                lat = position.coords.latitude;
                                lon = position.coords.longitude;
                                var zip = $('#mystore_zip').val();
                                var wsurl;
							   	wsurl = buildUrl(lat, lon);
                                $('#'+headerInnerDivId).html("");
                                locate.buildLoderHtml();
                                $.getJSON(wsurl + "&callback=ResultList", function (data) { })
                                    .fail(function () {
                                    	createBaseHtml();
                                        // showDefaultMessage();
                                        locate.removeLoderHtml();
                                    })
                                    .done(function (data) {
                                    	locate.removeLoderHtml();
                                        if (data.ResultList.length >0) {
                                        	locate.removeLoderHtml();
                                        	storeCount = 0;

                                        	createBaseHtml();

                                           for (var j=0; j < data.ResultList.length; j++ ) {
                                            
                                            var locationId = data.ResultList[j].Id != null ? data.ResultList[j].Id : "";
                                            var Distance = data.ResultList[j].Distance != null ? data.ResultList[j].Distance : "";
                                            var CountryCode = data.ResultList[j].CountryCode != null ? data.ResultList[j].CountryCode : "";
                                            var locName = data.ResultList[j].Name != null ? data.ResultList[j].Name : ""; 
											var address = data.ResultList[j].Address1 != null ? data.ResultList[j].Address1 : "";
                                            var city = data.ResultList[j].City != null ? data.ResultList[j].City : "";
                                            var state = data.ResultList[j].State != null ? data.ResultList[j].State : "";
                                            var zip = data.ResultList[j].PostCode != null ? data.ResultList[j].PostCode : "";
											var phone =  data.ResultList[j].PhoneNumber != null ? data.ResultList[j].PhoneNumber : "";
                                            var dataValStr = locationId  + '|' + locName + '|' + address + '|' + city + '|' + state + '|' + zip + '|' + phone;
                                            var latitude = data.ResultList[j].Latitude != null ? data.ResultList[j].Latitude : "";
                                            var longitude = data.ResultList[j].Longitude != null ? data.ResultList[j].Longitude : "";
                                            
                                            buildNewLocationHtml(locationId, locName, address, city, state, zip, phone, Distance, CountryCode, latitude, longitude);
                                            if (j == 0)  
                                              setCookie(beSrchCookieKey, dataValStr, 60);
                                          }  
                                        }
                                        else {
                                            createBaseHtml();
                                        }
                                    });
                            },
                            function (error) {
                                showDefaultMessage();
                                locate.removeLoderHtml();
                            }
                        );
		            } else {
		                showDefaultMessage();
		            }
		        },
		        getLocationByZip: function () {
			         var locate = this;
		            
                                var zip = $('#mystore_zip').val();
                                var wsurl;
							   if (zip.length == 5){
								    wsurl = buildUrlZip(zip);
								   
							   }
                                $('#'+headerInnerDivId).html("");
                                locate.buildLoderHtml();
                                $.getJSON(wsurl + "&callback=ResultList", function (data) { })
                                    .fail(function () {
                                    	createBaseHtml();
                                        // showDefaultMessage();
                                        locate.removeLoderHtml();
                                    })
                                    .done(function (data) {
                                    	locate.removeLoderHtml();
                                        if (data.ResultList.length >0) {
                                        	locate.removeLoderHtml();
                                        	storeCount = 0;

                                        	createBaseHtml();

                                           for (var j=0; j < data.ResultList.length; j++ ) {
                                            
                                            var locationId = data.ResultList[j].Id != null ? data.ResultList[j].Id : "";
                                            var Distance = data.ResultList[j].Distance != null ? data.ResultList[j].Distance : "";
                                            var CountryCode = data.ResultList[j].CountryCode != null ? data.ResultList[j].CountryCode : "";
                                            var locName = data.ResultList[j].Name != null ? data.ResultList[j].Name : ""; 
											var address = data.ResultList[j].Address1 != null ? data.ResultList[j].Address1 : "";
                                            var city = data.ResultList[j].City != null ? data.ResultList[j].City : "";
                                            var state = data.ResultList[j].State != null ? data.ResultList[j].State : "";
                                            var zip = data.ResultList[j].PostCode != null ? data.ResultList[j].PostCode : "";
											var phone =  data.ResultList[j].PhoneNumber != null ? data.ResultList[j].PhoneNumber : "";
                                            var dataValStr = locationId  + '|' + locName + '|' + address + '|' + city + '|' + state + '|' + zip + '|' + phone;
                                            var latitude = data.ResultList[j].Latitude != null ? data.ResultList[j].Latitude : "";
                                            var longitude = data.ResultList[j].Longitude != null ? data.ResultList[j].Longitude : "";
                                            
                                            buildNewLocationHtml(locationId, locName, address, city, state, zip, phone, Distance, CountryCode, latitude, longitude);
                                            if (j == 0)  
                                              setCookie(beSrchCookieKey, dataValStr, 60);
                                          }  
                                        }
                                        else {
                                            createBaseHtml();
                                        }
                                    });
                            },
                            
		     
		        buildBaseHtml: function () {
		            //var image_src = '<?php echo $this->getViewFileUrl('Bullseye_Locator::images/ajax-loader.gif')?>'
		            var headerInnerDiv = $('<div/>', { id: headerInnerDivId }).appendTo($('#' + headerDivId));
		            /*
		            $('<img/>', {
		                id: headerLoaderId,
		                src: image_src,
		                alt: 'loading...'
		            }).appendTo(headerInnerDiv);
*/
		        },
		         buildLoderHtml: function () {
		            var image_src = '<?php echo $this->getViewFileUrl('Bullseye_Locator::images/ajax-loader.gif')?>'
		            var headerInnerDiv = $('#'+headerInnerDivId);
		            $('<img/>', {
		                id: headerLoaderId,
		                src: image_src,
		                alt: 'loading...'
		            }).appendTo(headerInnerDiv);

		        },

		        removeLoderHtml: function () {
		            var loderImage = $('#'+headerLoaderId);
		            if(loderImage){
		            	loderImage.remove();
		            }

		        },
		        hasSearchCookie: function () {
		            var hasCookie;
		            var beSrchCookie = getCookie(beSrchCookieKey);

		            if (beSrchCookie!="") {
		                hasCookie = true;
		                var beSrchCookieArr = beSrchCookie.split('|');
		                buildNewLocationHtml(beSrchCookieArr[0], beSrchCookieArr[1], beSrchCookieArr[2], beSrchCookieArr[3], beSrchCookieArr[4], beSrchCookieArr[5], beSrchCookieArr[6]);
		            }
		            else
		                hasCookie = false;
		            return hasCookie;
		        }
		    }
		} (jQuery));

		
		$(function () {

		    bullseyeLocator.buildBaseHtml();

		    $( "#gpslocation_account" ).click(function() {
				bullseyeLocator.getLocation();
		   	}); 
		   	
		   	function errorAppend(message){
		   		$('#bullseye-banner-header-inner').html('');
		   		var error = $('.error-message');
		   		if(typeof error.html() === "undefined"){
		   			$('.erromessage').append('<div class="error-message">'+message+'</div>');
		   		}else{
		   			$('.error-message').html(message);
		   		}
		   	}

		   	$( "#mystore_Search" ).click(function() {
		   		var zip = $('#mystore_zip').val();
		   		if(zip){
		   			$('.error-message').remove();
		   			if (zip.length == 5){
				   		bullseyeLocator.getLocationByZip();
			   		}
			   		else {
			   			errorAppend('Require only 5 digits.');		
			   		}
		   		}
		   		else
		   		{
		   			errorAppend('Please enter zip code.');		   			
		   		}
		   	});
		});

	});
</script>